name: job-site
dependencies:
    - python=3
    - setuptools
    - ipython
    - flask
    - pip
    - pip:
        - requests
        - html2text
        - lxml
        - beautifulsoup4
        - flask-markdown
        - nose
        - mock
        - flask-wtf
